# Generated by Django 5.0.6 on 2024-06-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leituras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idlivro', models.IntegerField()),
                ('nomelivro', models.TextField(max_length=255)),
                ('lido', models.BooleanField(default=False)),
                ('resenha', models.TextField()),
            ],
        ),
    ]
