# Generated by Django 5.0.6 on 2024-06-01 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resenhaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leituras',
            name='idlivro',
        ),
    ]
